# This workflow uses actions that are not certified by GitHub.  They are
# provided by a third-party and are governed by separate terms of service,
# privacy policy, and support documentation.
#
# This workflow will install a prebuilt Ruby version, install dependencies, and
# run tests and linters.
name: "Ruby on Rails CI with MeiliSearch"
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11-alpine
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: rails_test
          POSTGRES_USER: rails
          POSTGRES_PASSWORD: password
      redis:
        image: redis
        ports: ['6379:6379']
        options: --entrypoint redis-server
      meilisearch:
        image: getmeili/meilisearch:latest
        ports:
          - "7701:7700" # Change external port to 7701, internal remains 7700
        env:
          MEILISEARCH_HTTP_ADDR: "http://localhost:7700" # Still reference internal port
    env:
      RAILS_ENV: test
      DATABASE_URL: "postgres://rails:password@localhost:5432/rails_test"
      MEILISEARCH_HOST: "http://localhost:7700"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@55283cc23133118229fd3f97f9336ee23a179fcf # v1.146.0
        with:
          bundler-cache: true
      - name: Set up database schema
        run: bin/rails db:schema:load
      - name: Start MeiliSearch
        run: |
          docker run -d -p 7701:7700 getmeili/meilisearch:latest # Use port 7701 externally
          sleep 5 # Adjust as needed for MeiliSearch to start up
      - name: Run tests with MeiliSearch
        run: |
          bin/rails test:prepare
          bin/rails db:test:prepare
          bundle exec rspec
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@55283cc23133118229fd3f97f9336ee23a179fcf # v1.146.0
        with:
          bundler-cache: true
      - name: Security audit dependencies
        run: bin/bundler-audit --update
      - name: Security audit application code
        run: bin/brakeman -q -w2
      - name: Lint Ruby files
        run: bin/rubocop --parallel


